// <auto-generated />
using System;
using EnvironmentMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnvironmentMonitor.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MeasurementDbContext))]
    [Migration("20260117221635_AddASensorsggregationType")]
    partial class AddASensorsggregationType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("HasMotionSensor")
                        .HasColumnType("bit");

                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentifier")
                        .IsUnique();

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("TypeId");

                    b.HasIndex("Name", "LocationId")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceAttachment", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<bool>("IsDefaultImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeviceImage")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("DeviceId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("[IsDefaultImage] = 1");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("DeviceAttachments");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("DeviceId", "TypeId")
                        .IsUnique();

                    b.HasIndex("TimeStamp", "DeviceId");

                    b.ToTable("DeviceAttributes");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceAttributeType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceAttributeTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Motion control status. 0=AlwaysOff,1=AlwaysOn,2=MotionControl",
                            Name = "MotionControlStatus",
                            Type = "int"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Output delay in ms when motion control is on.",
                            Name = "OnDelay",
                            Type = "int"
                        });
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("DeviceId", "Email")
                        .IsUnique();

                    b.ToTable("DeviceContacts");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TypeId");

                    b.HasIndex("TimeStamp", "DeviceId");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceEventType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceEventTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Reboot command",
                            Name = "RebootCommand"
                        },
                        new
                        {
                            Id = 1,
                            Description = "First message after boot / online since",
                            Name = "Online"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Set motion control status",
                            Name = "SetMotionControlStatus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Set motion control delays",
                            Name = "SetMotionControlDelay"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Send stored attributes",
                            Name = "SendAttributes"
                        });
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("FirstMessage")
                        .HasColumnType("bit");

                    b.Property<string>("Identifier")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("bit");

                    b.Property<long?>("LoopCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("MessageCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStampUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Uptime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TimeStamp");

                    b.HasIndex("DeviceId", "TimeStamp");

                    b.HasIndex("Identifier", "DeviceId")
                        .IsUnique()
                        .HasFilter("[Identifier] IS NOT NULL AND [IsDuplicate] = 0");

                    b.ToTable("DeviceMessages");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceQueuedCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OriginalId")
                        .HasColumnType("int");

                    b.Property<string>("PopReceipt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Scheduled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("OriginalId");

                    b.HasIndex("Type");

                    b.HasIndex("DeviceId", "ExecutedAtUtc");

                    b.HasIndex("DeviceId", "ScheduledUtc");

                    b.ToTable("DeviceQueuedCommands");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceQueuedCommandType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceQueuedCommandTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Send stored device attributes",
                            Name = "SendDeviceAttributes"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Set motion control status",
                            Name = "SetMotionControlStatus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Set motion control delay",
                            Name = "SetMotionControlOnDelay"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Send email about a device",
                            Name = "SendDeviceEmail"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Process forget user password request",
                            Name = "ProcessForgetUserPasswordRequest"
                        });
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<long?>("DeviceMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceMessageId");

                    b.HasIndex("TimeStamp", "DeviceId", "Status");

                    b.ToTable("DeviceStatusChanges");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Message")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Device connection lost"
                        },
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "Device connection restored"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = new Guid("00000000-0000-0000-0000-000000000000"),
                            Message = "Please confirm your email address by clicking the link below:\n\n{ConfirmationLink}\n\nIf you did not create an account, please ignore this email.",
                            Name = "Confirm Email",
                            Title = "Confirm Your Email Address"
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = new Guid("00000000-0000-0000-0000-000000000000"),
                            Message = "You have requested to reset your password. Please click the link below to set a new password:\n\n{ResetLink}\n\nIf you did not request a password reset, please ignore this email.",
                            Name = "User Password Reset",
                            Title = "Reset Your Password"
                        });
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.LocationSensor", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "SensorId", "DeviceId");

                    b.HasIndex("TypeId");

                    b.HasIndex("DeviceId", "LocationId");

                    b.HasIndex("SensorId", "DeviceId");

                    b.ToTable("LocationSensors");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("DeviceMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceMessageId");

                    b.HasIndex("SensorId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TypeId");

                    b.HasIndex("SensorId", "Timestamp");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SensorId", "Timestamp"), new[] { "Value", "TypeId", "TimestampUtc" });

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.MeasurementType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeasurementTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Undefined",
                            Unit = "-"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Temperature",
                            Unit = "C"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Humidity",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Light",
                            Unit = "Lx"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Motion",
                            Unit = "ON/OFF"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pressure",
                            Unit = "-"
                        });
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.PublicSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("SensorId")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("PublicSensors");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AggregationType")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double?>("ScaleMax")
                        .HasColumnType("float");

                    b.Property<double?>("ScaleMin")
                        .HasColumnType("float");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.HasIndex("DeviceId", "SensorId")
                        .IsUnique();

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.SensorType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SensorTypes");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.VirtualSensorRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("ValueSensorId")
                        .HasColumnType("int");

                    b.Property<int>("VirtualSensorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("ValueSensorId");

                    b.HasIndex("VirtualSensorId", "ValueSensorId")
                        .IsUnique();

                    b.ToTable("VirtualSensorRows");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Device", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Location", "Location")
                        .WithMany("Devices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceType", "Type")
                        .WithMany("Devices")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceAttachment", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Attachment", "Attachment")
                        .WithMany("DeviceAttachments")
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("Attachments")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceAttribute", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("DeviceAttributes")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceAttributeType", "Type")
                        .WithMany("DeviceAttributes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceContact", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("Contacts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceEvent", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("Events")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceEventType", "Type")
                        .WithMany("Events")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceMessage", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("DeviceMessages")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceQueuedCommand", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("QueuedCommands")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceQueuedCommand", "OriginalCommand")
                        .WithMany()
                        .HasForeignKey("OriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceQueuedCommandType", "CommandType")
                        .WithMany("QueuedCommands")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommandType");

                    b.Navigation("Device");

                    b.Navigation("OriginalCommand");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceStatus", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("StatusChanges")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceMessage", "DeviceMessage")
                        .WithMany("DeviceStatuses")
                        .HasForeignKey("DeviceMessageId");

                    b.Navigation("Device");

                    b.Navigation("DeviceMessage");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.LocationSensor", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Location", "Location")
                        .WithMany("LocationSensors")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.MeasurementType", "MeasurementType")
                        .WithMany("LocationSensors")
                        .HasForeignKey("TypeId");

                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("LocationSensors")
                        .HasForeignKey("DeviceId", "LocationId")
                        .HasPrincipalKey("Id", "LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.Sensor", "Sensor")
                        .WithMany("LocationSensors")
                        .HasForeignKey("SensorId", "DeviceId")
                        .HasPrincipalKey("Id", "DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Location");

                    b.Navigation("MeasurementType");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.DeviceMessage", "DeviceMessage")
                        .WithMany("Measurements")
                        .HasForeignKey("DeviceMessageId");

                    b.HasOne("EnvironmentMonitor.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Measurements")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.MeasurementType", "Type")
                        .WithMany("Measurements")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceMessage");

                    b.Navigation("Sensor");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.PublicSensor", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Sensor", "Sensor")
                        .WithMany("PublicSensors")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnvironmentMonitor.Domain.Entities.MeasurementType", "MeasurementType")
                        .WithMany("PublicSensors")
                        .HasForeignKey("TypeId");

                    b.Navigation("MeasurementType");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.Device", "Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnvironmentMonitor.Domain.Entities.SensorType", "Type")
                        .WithMany("Sensors")
                        .HasForeignKey("TypeId");

                    b.Navigation("Device");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.VirtualSensorRow", b =>
                {
                    b.HasOne("EnvironmentMonitor.Domain.Entities.MeasurementType", "Type")
                        .WithMany("VirtualSensorRows")
                        .HasForeignKey("TypeId");

                    b.HasOne("EnvironmentMonitor.Domain.Entities.Sensor", "ValueSensor")
                        .WithMany("VirtualSensorRowValues")
                        .HasForeignKey("ValueSensorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnvironmentMonitor.Domain.Entities.Sensor", "VirtualSensor")
                        .WithMany("VirtualSensorRows")
                        .HasForeignKey("VirtualSensorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Type");

                    b.Navigation("ValueSensor");

                    b.Navigation("VirtualSensor");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Attachment", b =>
                {
                    b.Navigation("DeviceAttachments");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Device", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Contacts");

                    b.Navigation("DeviceAttributes");

                    b.Navigation("DeviceMessages");

                    b.Navigation("Events");

                    b.Navigation("LocationSensors");

                    b.Navigation("QueuedCommands");

                    b.Navigation("Sensors");

                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceAttributeType", b =>
                {
                    b.Navigation("DeviceAttributes");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceEventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceMessage", b =>
                {
                    b.Navigation("DeviceStatuses");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceQueuedCommandType", b =>
                {
                    b.Navigation("QueuedCommands");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Location", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("LocationSensors");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.MeasurementType", b =>
                {
                    b.Navigation("LocationSensors");

                    b.Navigation("Measurements");

                    b.Navigation("PublicSensors");

                    b.Navigation("VirtualSensorRows");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("LocationSensors");

                    b.Navigation("Measurements");

                    b.Navigation("PublicSensors");

                    b.Navigation("VirtualSensorRowValues");

                    b.Navigation("VirtualSensorRows");
                });

            modelBuilder.Entity("EnvironmentMonitor.Domain.Entities.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
