export const routes = {
  main: "/",
  home: "/home",
  login: "/login",
  register: "/register",
  emailConfirmation: "/email-confirmation",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-password",
  userInfo: "/user-info",
  measurements: "/measurements/device",
  measurementsByDevice: "/measurements/device/:deviceId",
  locationMeasurements: "/measurements/location",
  measurementsByLocation: "/measurements/location/:locationId",
  dashboard: "/dashboard",
  locationDashboard: "/dashboard/location",
  devices: "/devices",
  deviceView: "/devices/:deviceId",
  deviceMessages: "/devices/messages",
  deviceEmails: "/device-emails",
};
