export const routes = {
  main: "/",
  home: "/home",
  login: "/login",
  loginInfo: "/login/info",
  register: "/register",
  emailConfirmation: "/email-confirmation",
  resetPassword: "/set-new-password",
  forgotPassword: "/forgot-password",
  userInfo: "/user-info",
  measurements: "/measurements/device",
  measurementsByDevice: "/measurements/device/:deviceId",
  locationMeasurements: "/measurements/location",
  measurementsByLocation: "/measurements/location/:locationId",
  publicMeasurements: "/measurements/public",
  dashboard: "/dashboard",
  locationDashboard: "/dashboard/location",
  devices: "/devices",
  deviceView: "/devices/:deviceId",
  deviceMessages: "/devices/messages",
  deviceEmails: "/device-emails",
  users: "/users",
  userView: "/users/:userId",
  apiKeys: "/api-keys",
};
