name: Build and deploy environment-monitor

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: "Run Deploy Job?"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.0.0"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Install LocalDB
      - name: Install LocalDB
        uses: potatoqualitee/mssqlsuite@v1.8
        with:
          install: localdb

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with the dotnet CLI
        run: |
          dotnet test tests/EnvironmentMonitor.Tests/EnvironmentMonitor.Tests.csproj

      - name: Install dependencies for React UI
        run: |
          cd src/EnvironmentMonitor.ReactUi/environment-monitor
          npm install

      - name: Build React UI (Vite)
        run: |
          cd src/EnvironmentMonitor.ReactUi/environment-monitor
          npm run build

      - name: Copy Vite build to .NET wwwroot
        run: |
          cp -r src/EnvironmentMonitor.ReactUi/environment-monitor/dist/ src/EnvironmentMonitor.WebApi/wwwroot/

      - name: Publish WEB API (WIN-X86, WIN-X64, LINUX-X64)
        run: |
          dotnet publish src/EnvironmentMonitor.WebApi/EnvironmentMonitor.WebApi.csproj -c Release -r win-x86 -o "${{env.DOTNET_ROOT}}/env-monitor-web-api_x86"
          dotnet publish src/EnvironmentMonitor.WebApi/EnvironmentMonitor.WebApi.csproj -c Release -r win-x64 -o "${{env.DOTNET_ROOT}}/env-monitor-web-api_x64"
          dotnet publish src/EnvironmentMonitor.WebApi/EnvironmentMonitor.WebApi.csproj -c Release -r linux-x64 -o "${{env.DOTNET_ROOT}}/env-monitor-web-api_linux-x64"

      - name: Publish Function app (WIN-X86, WIN-X64, LINUX-X64)
        run: |
          dotnet publish src/EnvironmentMonitor.HubObserver/EnvironmentMonitor.HubObserver.csproj -c Release -r win-x86 -o "${{env.DOTNET_ROOT}}/env-monitor-function_x86"
          dotnet publish src/EnvironmentMonitor.HubObserver/EnvironmentMonitor.HubObserver.csproj -c Release -r win-x64 -o "${{env.DOTNET_ROOT}}/env-monitor-function_x64"
          dotnet publish src/EnvironmentMonitor.HubObserver/EnvironmentMonitor.HubObserver.csproj -c Release -r linux-x64 -o "${{env.DOTNET_ROOT}}/env-monitor-function_linux-x64"

      - name: Upload web api artifact (win-x86)
        uses: actions/upload-artifact@v4
        with:
          name: .env-monitor-web-api_x86
          path: ${{env.DOTNET_ROOT}}/env-monitor-web-api_x86

      - name: Upload web api artifact (win-x64)
        uses: actions/upload-artifact@v4
        with:
          name: .env-monitor-web-api_x64
          path: ${{env.DOTNET_ROOT}}/env-monitor-web-api_x64

      - name: Upload web api artifact (linux-x64)
        uses: actions/upload-artifact@v4
        with:
          name: .env-monitor-web-api_linux-x64
          path: ${{env.DOTNET_ROOT}}/env-monitor-web-api_linux-x64

      - name: Upload function artifact (win-x86)
        uses: actions/upload-artifact@v4
        with:
          name: .env-monitor-function_x86
          path: ${{env.DOTNET_ROOT}}/env-monitor-function_x86
          include-hidden-files: true

      - name: Upload function artifact (win-x64)
        uses: actions/upload-artifact@v4
        with:
          name: .env-monitor-function_x64
          path: ${{env.DOTNET_ROOT}}/env-monitor-function_x64
          include-hidden-files: true
  deploy:
    runs-on: windows-latest
    needs: build
    if: github.event_name == 'push' || inputs.deploy == 'true'
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download WEB API artifacts (WIN-X86)
        uses: actions/download-artifact@v4
        with:
          name: .env-monitor-web-api_x86
          path: "./env-monitor-web-api"

      - name: Download WEB API artifacts (LINUX-X64)
        uses: actions/download-artifact@v4
        with:
          name: .env-monitor-web-api_linux-x64
          path: "./env-monitor-web-api_linux-x64"

      - name: Download Function artifacts (WIN-X64)
        uses: actions/download-artifact@v4
        with:
          name: .env-monitor-function_x64
          path: "./env-monitor-function"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C8625311A7E41DF94B1F493E439AE3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9F03B52F6CA485B82924F1970E00D80 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4CE7A1599994A388FDDA5640CED3ECE }}

      - name: Deploy Environment Monitor Web API
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "env-monitor"
          slot-name: "Production"
          package: "./env-monitor-web-api"

      - name: Deploy Environment Monitoring Web API (LINUX)
        id: deploy-to-webapp-linux
        uses: azure/webapps-deploy@v3
        with:
          app-name: "environment-monitoring"
          slot-name: "Production"
          package: "./env-monitor-web-api_linux-x64"

      - name: "Deploy HubObserver (Azure function)"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "EnvironmentMonitorHubObserver"
          slot-name: "Production"
          package: "./env-monitor-function"
